# this will generate the acme_ca.crt and acme_ca.key at ./examples/letsacme/
# you can trust the acme_ca.crt in your system.

services:
  letsacme:
    image: ikidou/letsacme
    container_name: letsacme
    ports:
      - "3000:3000"
    volumes:
      - "./examples/letsacme:/data"
    restart: always
    command: ["-https"]