name: Build Docker Image
on:
  push:
    branches:
      - release
    paths:
      - ".github/workflows/docker_build.yaml"
      - "Dockerfile"
      - "go.mod"
      - "*.go"
  workflow_dispatch:
    inputs:
      push2Repo:
        description: 'Push to Repositorys'
        required: false
        type: boolean
        default: false

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Docker Setup QEMU
        # https://github.com/docker/setup-qemu-action/releases
        uses: docker/setup-qemu-action@v4.0.0

      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action/releases
        uses: docker/setup-buildx-action@v4.0.0
        with:
          driver: docker-container

      - name: Check out the repo
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v5.0.1

      - name: Log in to Docker Hub
        # https://github.com/docker/login-action/releases
        uses: docker/login-action@v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        # https://github.com/docker/login-action/releases
        uses: docker/login-action@v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        #https://github.com/docker/metadata-action/releases
        uses: docker/metadata-action@v6.0.0
        with:
          images: |
            ikidou/letsacme
            ghcr.io/ikidou/letsacme
          tags: |
            type=ref,event=tag  
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{branch}},enable={{is_not_default_branch}}
            type=raw,value={{date 'YYYYMMDD' tz='Asia/Shanghai'}}

      - name: Build and push Docker images
        id: push
        # https://github.com/docker/build-push-action/releases
        uses: docker/build-push-action@v7.0.0
        with:
          provenance: false
          platforms: |
            linux/amd64
            linux/arm64
          context: ./
          push: ${{ github.event_name != 'workflow_dispatch' || inputs.push2Repo }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker Hub Description
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.push2Repo }}
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ikidou/letsacme
          readme-filepath: ./README.md